### ISSUE TITLE
Shops show all 4 Items as being Checks regardless of Settings

### ISSUE THREAD

**Issue by Deathclaw99** [StripesOO7/oot-tracker#20]
No matter how high the Shopsanity slots rolled, every shop shows 4 Items as being a check on the tracker.

**Comment by StripesOO7** [comment]
I have just added a functoin to fix this issue. 

if **connected** it will check for the exact shop locations that are available

if **NOT connected** it will show them in order based on the shop slot setting. (random value wont work for this. its all same the same nuber shown because i dont want to make counters for all individual shops just for this edge case in offline use)

**Comment by StripesOO7** [comment]
![grafik](https://github.com/user-attachments/assets/cadd5af8-61e9-4fa5-8a57-19e7a5166a47)
